### ISSUE TITLE
v1.2.5 can not use locale DE

### ISSUE THREAD

**Issue by WuglyakBolgoink** [mjwheatley/cordova-plugin-android-fingerprint-auth#61]
I use following config:
```
var decryptConfig = {
                        clientId: getServiceName(),
                        username: getEmail(),
                        token: getToken(),
                        disableBackup: true,
                        dialogTitle: TOUCH_VIA_ANDROID,
                        locale: 'de'
};
```

FP-Dialog show all strings on english! But if I try to do it quickly, so I can see error-text on germany language.

if I change locale config on "ru" or "es" it work fine!
- FPA__de_default
    ![fpa__de_default](https://cloud.githubusercontent.com/assets/2271337/23613672/ba0f64de-0280-11e7-91e7-d874c5b55a42.png)
- FPA__de_error1
    ![fpa__de_error1](https://cloud.githubusercontent.com/assets/2271337/23613675/ba1323f8-0280-11e7-8fec-b362bfb3a765.png)
- fpa__de_error2
    ![fpa__de_error2](https://cloud.githubusercontent.com/assets/2271337/23613673/ba12bff8-0280-11e7-9d86-fb80e92ece41.png)
- fpa__ru_default
    ![fpa__ru_default](https://cloud.githubusercontent.com/assets/2271337/23613674/ba149350-0280-11e7-9538-a48616751dbd.png)
- fpa__ru_error1
    ![fpa__ru_error1](https://cloud.githubusercontent.com/assets/2271337/23613676/ba205050-0280-11e7-8064-adb96f44b916.png)

**Comment by mjwheatley** [comment]
Can you confirm that the `values-de` directory was copied from the plugin into your Android project?

**Comment by WuglyakBolgoink** [comment]
Hallo @mjwheatley!

Hm...

- EXIST: `<project>/plugins/cordova-plugin-android-fingerprint-auth/res/android/values-de/fpauth-strings.xml`
- in `<project>/platforms/android/res` not found...

```
platforms
	android
		.gradle
		assets
		build
		cordova
		cordova-plugin-crosswalk-webview
		cordova-plugin-iroot
		CordovaLib
		gradle
		libs
		platform_www
		res
			drawable
			. . .
			values
			values-es
			values-fr
			values-it
			values-ja
			values-no
			values-pt
			values-ru
			values-zh
			values-zh-rCN
			values-zh-rHK
			values-zh-rMO
			values-zh-rSG
			values-zh-rTW
			xml
		src
```

**Comment by mjwheatley** [comment]
You can manually copy the file to the appropriate directory or try removing and reinstalling the plugin.  Just make sure the file is added to your project and that should resolve your issue.

**Comment by WuglyakBolgoink** [comment]
Hallo @mjwheatley 

reinstall can not help me... `values-de` was not copy automatically into platforms folder!

```bash
cordova --v
#6.5.0

npm -v
#4.3.0

cordova plugins list
#cordova-plugin-android-fingerprint-auth 1.2.5 "FingerprintAuth"

cordova platforms list
# Installed platforms:
#   android 6.1.2

```

**Comment by WuglyakBolgoink** [comment]
Hallo @mjwheatley 

found ))

you forgot add this file in `plugin.xml`

```
        <source-file src="res/android/values-it" target-dir="res" />
        <source-file src="res/android/values-es" target-dir="res" />
        <source-file src="res/android/values-ru" target-dir="res" />
        <source-file src="res/android/values-fr" target-dir="res" />
        <source-file src="res/android/values-zh" target-dir="res" />
        <source-file src="res/android/values-zh-rCN" target-dir="res" />
        <source-file src="res/android/values-zh-rHK" target-dir="res" />
        <source-file src="res/android/values-zh-rMO" target-dir="res" />
        <source-file src="res/android/values-zh-rSG" target-dir="res" />
        <source-file src="res/android/values-zh-rTW" target-dir="res" />
        <source-file src="res/android/values-no" target-dir="res" />
        <source-file src="res/android/values-pt" target-dir="res" />
        <source-file src="res/android/values-ja" target-dir="res" />
```

**Comment by mjwheatley** [comment]
I have published version 1.2.6 to fix this issue.  Please update to the new version and verify that it resolves the problem for you.  Thanks for helping to find the problem.

**Comment by lordgreg** [comment]
It does not. This issue still exists, even when only installing the plugin:
```
Installing "cordova-plugin-android-fingerprint-auth" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-android-fingerprint-auth':Error
    at copyNewFile (/Users/USER/Projects/MY_PROJECT/platforms/android/cordova/lib/pluginHandlers.js:232:15)
    at install (/Users/USER/Projects/MY_PROJECT/platforms/android/cordova/lib/pluginHandlers.js:37:17)
    at ActionStack.process (/Users/USER/Projects/MY_PROJECT/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/Users/USER/Projects/MY_PROJECT/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:117:20)
    at PluginManager.addPlugin (/Users/USER/Projects/MY_PROJECT/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:147:17)
    at Api.addPlugin (/Users/USER/Projects/MY_PROJECT/platforms/android/cordova/Api.js:198:10)
    at handleInstall (/Users/USER/Projects/MY_PROJECT/node_modules/cordova-lib/src/plugman/install.js:611:6)
    at /Users/USER/Projects/MY_PROJECT/node_modules/cordova-lib/src/plugman/install.js:407:28
    at _fulfilled (/Users/USER/Projects/MY_PROJECT/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/USER/Projects/MY_PROJECT/node_modules/q/q.js:816:30)
Failed to restore plugin "cordova-plugin-android-fingerprint-auth" from config.xml. You might need to try adding it again. Error: Uh oh!
"/Users/USER/Projects/MY_PROJECT/platforms/android/res/values-de" already exists!
```

**Comment by WuglyakBolgoink** [comment]
Hi @lordgreg 

my test now:

- install plugin in config.xml with `-- save` option
- delete android platform
- install android platform

result:
- `values-de` exist in `res` folder
- no compile/install errors

**Comment by lordgreg** [comment]
Hi @WuglyakBolgoink for your answer.

My test:

- install plugin with `--save`.
- delete platform
- `cordova prepare`

result:

- error above

**Comment by WuglyakBolgoink** [comment]
@lordgreg 

do you have this property in your `config.xml`? because I can't reproduce your error...

```xml
    <preference name="cordova-custom-config-autorestore" value="false" />
```

or try
- delete plugin with --save
- delete platform
- add platform
- add plugin with --save
- do "cordova prepare"

**Comment by lordgreg** [comment]
@WuglyakBolgoink 
- I don't see the reason why I should use the preference you're mentioning above?
- My current cordova version is 6.3.1. What is yours?
- Why are you always adding platform? If you have the engine property in `config.xml`, cordova itself will install platform if it doesn't find the proper folder inside `platforms`?
- What engine are you installing? I've tried with android 5.2.2 and 6.1.2 (cordova engines)

**Comment by WuglyakBolgoink** [comment]
@lordgreg 

- I use [cordova-custom-config](https://www.npmjs.com/package/cordova-custom-config)
- My Cordova - v6.5.0
- I always remove platforms/plugins with `--save` option. 😹  deep cleaning 
- Android - v6.1.2

**Comment by lordgreg** [comment]
Interesting,

prepare doesn't work like that and I see it as conflict because, all other plugins that I use in the project:
```
    <plugin name="com.mwaysolutions.cordova.webviewplugin" spec="https://github.com/mwaylabs/cordova-plugin-inappbrowser.git" />
    <plugin name="cordova-plugin-x-toast" spec="~2.2.0" />
    <plugin name="cordova-plugin-globalization" spec="~1.0.1" />
    <plugin name="cordova-plugin-whitelist" spec="~1.0.0" />
    <plugin name="phonegap-plugin-push" spec="~1.4.5" />
    <plugin name="cordova-plugin-screen-orientation" spec="~1.4.0" />
    <plugin name="cordova-plugin-appinfo" spec="~2.0.3" />
    <plugin name="cordova-plugin-apteligent" spec="~3.1.0" />
    <engine name="ios" spec="~4.3.1" />
    <engine name="android" spec="~5.2.2" />
    <plugin name="cordova-plugin-device" spec="~1.1.3" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-network-information" spec="~1.3.0" />
    <plugin name="cordova-plugin-splashscreen" spec="~4.0.0" />
    <plugin name="cordova-plugin-statusbar" spec="~2.2.0" />
    <plugin name="cordova-plugin-touch-id" spec="~3.2.0" />
```

...work as charm. I'm sticking with 1.2.5 until this issue is resolved.

**Comment by WuglyakBolgoink** [comment]
Hi @lordgreg 

Do you have always same error?
```
Failed to restore plugin "cordova-plugin-android-fingerprint-auth" from config.xml. You might need to try adding it again. Error: Uh oh!
"/Users/USER/Projects/MY_PROJECT/platforms/android/res/values-de" already exists!
```

**Comment by lordgreg** [comment]
Always :) with last version that is.

**Comment by mjwheatley** [comment]
@lordgreg have you uninstalled and removed all plugin files from your project and then try reinstalling?

**Comment by lordgreg** [comment]
@mjwheatley Thank you for responding.

I did. Before each test, I rimrafed `plugins` and `platforms`.

**Comment by WuglyakBolgoink** [comment]
@lordgreg  please 

- create a new cordova project
- add android platform
- add plugin

do you have same error? If no, then you have problem in your project folder and not with this plugin...

**Comment by Vamsi7591** [comment]
If you are installed **cordova-plugin-file** and trying add **cordova-plugin-android-fingerprint-auth** to project first take a backup of following XML files in folders and remove it temporarily 

1. values-de --> multiimagechooser_strings_de
2. values-ja --> multiimagechooser_strings_ja
3. values-es --> multiimagechooser_strings_es
4. values-fr --> multiimagechooser_strings_fr
 
**Next :** Install plugin 

> $ ionic plugin add cordova-plugin-android-fingerprint-auth
> $ npm install --save @ionic-native/android-fingerprint-auth

And add the removed xml files to respective folders and build.

It's working :100: % for me instead of removing and adding platforms.

Cheers :+1:
